const mongoose = require('mongoose');

const analysisSchema = new mongoose.Schema({
  // Link to the user who requested the analysis
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },
  // The original text extracted from the image by the AI
  originalText: {
    type: String,
    required: true,
  },
  // The simplified explanation generated by the AI
  simplifiedText: {
    type: String,
    required: true,
  },
  // The type of document that was analyzed
  documentType: {
    type: String,
    enum: ['Prescription', 'Lab Report', 'Other'],
    default: 'Other',
  },
}, {
  timestamps: true,
});

const Analysis = mongoose.model('Analysis', analysisSchema);

module.exports = Analysis;