import mongoose from "mongoose";

const analysisSchema = new mongoose.Schema(
  {
    // Link to the user who requested the analysis
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // The original text extracted from the image by the AI
    originalText: {
      type: String,
      required: true,
    },
    // The simplified explanation generated by the AI
    simplifiedText: {
      type: String,
      required: true,
    },
    // The type of document that was analyzed
    documentType: {
      type: String,
      enum: ["Prescription", "Lab Report", "Other"],
      default: "Other",
    },
  },
  {
    timestamps: true,
  },
);

export const Analysis = mongoose.model("Analysis", analysisSchema);